# Generated by Django 4.2 on 2023-04-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecentWork',
            new_name='Experience',
        ),
    ]
